name: MLflow CI Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  run-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mlflow pandas scikit-learn

      - name: Run MLProject
        run: |
          cd Workflow-CI/MLProject
          mlflow run . --env-manager=local

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: Workflow-CI/MLProject/mlruns/